<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testng-results failed="1" passed="0" skipped="0" total="1">
<suite duration-ms="20119" name="io.cucumber.core.plugin.TestNGFormatter">
<test duration-ms="20119" name="io.cucumber.core.plugin.TestNGFormatter">
<class name="Aperture Create Account,Search Account &amp; Edit Account">
<test-method duration-ms="11774" finished-at="2020-06-18T15:18:27.587Z" name="Validate Create Account Search Account &amp; Edit Account" started-at="2020-06-18T15:18:15.811Z" status="FAIL">
<exception class="java.lang.AssertionError">
<message><![CDATA[Given This is my first feature..............................................failed
]]></message>
<full-stacktrace><![CDATA[java.lang.AssertionError: expected:<5> but was:<6>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at com.gspann.aperture.steps.AccountStep.this_is_my_first_feature(AccountStep.java:29)
	at âœ½.This is my first feature(file:///E:/Apparture/Aperture-Project/MVN/aperture/src/test/resources/features/1-AccountCreate.feature:6)
]]></full-stacktrace>
</exception>
</test-method>
</class>
</test>
</suite>
</testng-results>
